# Generated by Django 3.0.7 on 2020-06-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('wins', models.CharField(max_length=10)),
                ('losses', models.CharField(max_length=10)),
                ('ties', models.CharField(max_length=10)),
                ('points_for', models.CharField(max_length=10)),
                ('points_against', models.CharField(max_length=10)),
                ('rush_td', models.CharField(max_length=10)),
                ('pass_td', models.CharField(max_length=10)),
                ('total_td', models.CharField(max_length=10)),
                ('pass_yards', models.CharField(max_length=10)),
                ('rush_yards', models.CharField(max_length=10)),
                ('int_for', models.CharField(max_length=10)),
                ('int_against', models.CharField(max_length=10)),
                ('forced_fumbles', models.CharField(max_length=10)),
                ('fumbles_recovered', models.CharField(max_length=10)),
                ('sacks', models.CharField(max_length=10)),
                ('fumble_td', models.CharField(max_length=10)),
                ('int_td', models.CharField(max_length=10)),
                ('safeties', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=10)),
                ('week', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('away_spread', models.CharField(max_length=10)),
                ('home_spread', models.CharField(max_length=10)),
                ('over_under', models.CharField(max_length=10)),
                ('away_score', models.CharField(max_length=10)),
                ('home_score', models.CharField(max_length=10)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='nflanalysis.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='nflanalysis.Team')),
            ],
        ),
    ]
