# Generated by Django 3.0.7 on 2020-06-13 03:39

from django.db import migrations

# TEAM MODEL

# team_name='',
# conference='',
# division='',
# wins='',
# losses='',
# ties='',
# points_for='',
# points_against='',
# rush_td='',
# pass_td='',
# total_td='',
# pass_yards='',
# rush_yards='',
# int_for='',
# forced_fumbles='',
# fumbles_recovered='',
# sacks='',
# fumble_td='',
# int_td='',
# safeties=''

# variable = Team(team_name='', conference='', division='', wins='', losses='', ties='0', points_for='', points_against='', rush_td='', pass_td='', total_td='', pass_yards='', rush_yards='', int_for='', forced_fumbles='', fumbles_recovered='', sacks='', fumble_td='', int_td='', safeties='')

# GAME MODEL

# game_id='',
# week='',
# day='',
# date='',
# away_team = ,
# away_spread='',
# home_team = ,
# home_spread='',
# over_under='',
# away_score='',
# home_score=''


def seed(apps, schema_editor):
    Team = apps.get_model('nflanalysis', 'Team')
    Game = apps.get_model('nflanalysis', 'Game')

    sf = Team(team_name='San Francisco 49ers', conference='NFC', division='West', wins='13', losses='3', ties='0', points_for='479', points_against='310', rush_td='23', pass_td='28',
              total_td='56', pass_yards='4029', rush_yards='2305', int_for='12', forced_fumbles='23', fumbles_recovered='15', sacks='36', fumble_td='2', int_td='3', safeties='0')
    chi = Team(team_name='Chicago Bears', conference='NFC', division='North', wins='8', losses='8', ties='0', points_for='280', points_against='298', rush_td='8', pass_td='20',
               total_td='30', pass_yards='3573', rush_yards='1458', int_for='10', forced_fumbles='12', fumbles_recovered='9', sacks='45', fumble_td='0', int_td='1', safeties='1')
    cin = Team(team_name='Cincinnati Bengals', conference='AFC', division='North', wins='2', losses='14', ties='0', points_for='279', points_against='420', rush_td='9', pass_td='18',
               total_td='28', pass_yards='3994', rush_yards='1517', int_for='11', forced_fumbles='9', fumbles_recovered='5', sacks='48', fumble_td='0', int_td='0', safeties='1')
    buf = Team(team_name='Buffalo Bills', conference='AFC', division='East', wins='10', losses='6', ties='0', points_for='314', points_against='259', rush_td='13', pass_td='21',
               total_td='35', pass_yards='3476', rush_yards='2054', int_for='14', forced_fumbles='16', fumbles_recovered='9', sacks='40', fumble_td='0', int_td='0', safeties='1')
    den = Team(team_name='Denver Broncos', conference='AFC', division='West', wins='7', losses='9', ties='0', points_for='282', points_against='316', rush_td='11', pass_td='16',
               total_td='28', pass_yards='3401', rush_yards='1662', int_for='10', forced_fumbles='9', fumbles_recovered='6', sacks='41', fumble_td='1', int_td='0', safeties='0')
    cle = Team(team_name='Cleveland Browns', conference='AFC', division='North', wins='6', losses='10', ties='0', points_for='335', points_against='393', rush_td='15', pass_td='22',
               total_td='38',	pass_yards='3847', rush_yards='1901', int_for='14', forced_fumbles='12', fumbles_recovered='6', sacks='41', fumble_td='0', int_td='1', safeties='0')
    tb = Team(team_name='Tampa Bay Buccaneers', conference='NFC', division='South', wins='7', losses='9', ties='0', points_for='458', points_against='449', rush_td='15', pass_td='33',
              total_td='54', pass_yards='5127', rush_yards='1521', int_for='12', forced_fumbles='21', fumbles_recovered='16', sacks='47', fumble_td='4', int_td='2', safeties='0')
    ari = Team(team_name='Arizona Cardinals', conference='NFC', division='West', wins='5', losses='10', ties='1', points_for='361', points_against='442', rush_td='18', pass_td='20',
               total_td='38', pass_yards='3797', rush_yards='1990', int_for='7', forced_fumbles='19', fumbles_recovered='10', sacks='50', fumble_td='0', int_td='0', safeties='0')
    lac = Team(team_name='Los Angeles Chargers', conference='AFC', division='West', wins='5', losses='11', ties='0', points_for='337', points_against='345', rush_td='12',
               pass_td='24', total_td='37',	pass_yards='4648',	rush_yards='1453', int_for='11', forced_fumbles='6', fumbles_recovered='3', sacks='34', fumble_td='0', int_td='0', safeties='0')
    kc = Team(team_name='Kansas City Chiefs', conference='AFC', division='West', wins='12', losses='4', ties='0', points_for='451',	points_against='308', rush_td='16', pass_td='30',
              total_td='50', pass_yards='4690', rush_yards='1569', int_for='16', forced_fumbles='13', fumbles_recovered='7', sacks='25', fumble_td='2', int_td='1', safeties='0')
    ind = Team(team_name='Indianapolis Colts',	conference='AFC',	division='South',	wins='7',	losses='9',	ties='0',	points_for='361',	points_against='373',	rush_td='17',	pass_td='22',
               total_td='42',	pass_yards='3314',	rush_yards='2130',	int_for='15',	forced_fumbles='14',	fumbles_recovered='8',	sacks='32',	fumble_td='0',	int_td='1',	safeties='2')
    dal = Team(team_name='Dallas Cowboys',	conference='NFC',	division='East',	wins='8',	losses='8',	ties='0',	points_for='434',	points_against='321',	rush_td='18',	pass_td='30',
               total_td='49',	pass_yards='4902',	rush_yards='2153',	int_for='7',	forced_fumbles='14',	fumbles_recovered='10',	sacks='23',	fumble_td='1',	int_td='0',	safeties='0')
    mia = Team(team_name='Miami Dolphins',	conference='AFC',	division='East',	wins='5',	losses='11',	ties='0',	points_for='306',	points_against='494',	rush_td='10',	pass_td='22',
               total_td='34',	pass_yards='4117',	rush_yards='1156',	int_for='13',	forced_fumbles='9',	fumbles_recovered='3',	sacks='58',	fumble_td='0',	int_td='1',	safeties='1')
    phi = Team(team_name='Philadelphia Eagles',	conference='NFC',	division='East',	wins='9',	losses='7',	ties='0',	points_for='385',	points_against='354',	rush_td='16',	pass_td='27',
               total_td='46',	pass_yards='4063',	rush_yards='1939',	int_for='11',	forced_fumbles='15',	fumbles_recovered='9',	sacks='37',	fumble_td='2',	int_td='1',	safeties='0')
    atl = Team(team_name='Atlanta Falcons',	conference='NFC',	division='South',	wins='7',	losses='9',	ties='0',	points_for='381',	points_against='399',	rush_td='10',	pass_td='29',
               total_td='42',	pass_yards='5049',	rush_yards='1361',	int_for='12',	forced_fumbles='17',	fumbles_recovered='8',	sacks='50',	fumble_td='1',	int_td='1',	safeties='0')
    nyg = Team(team_name='New York Giants',	conference='NFC',	division='East',	wins='4',	losses='12',	ties='0',	points_for='341',	points_against='451',	rush_td='11',	pass_td='30',
               total_td='44',	pass_yards='4070',	rush_yards='1685',	int_for='10',	forced_fumbles='9',	fumbles_recovered='6',	sacks='43',	fumble_td='1',	int_td='1',	safeties='1')
    jax = Team(team_name='Jacksonville Jaguars',	conference='AFC',	division='South',	wins='6',	losses='10',	ties='0',	points_for='300',	points_against='397',	rush_td='3',	pass_td='24',
               total_td='29',	pass_yards='4023',	rush_yards='1708',	int_for='10',	forced_fumbles='13',	fumbles_recovered='9',	sacks='42',	fumble_td='1',	int_td='1',	safeties='0')
    nyj = Team(team_name='New York Jets',	conference='AFC',	division='East',	wins='7',	losses='9',	ties='0',	points_for='276',	points_against='359',	rush_td='6',	pass_td='19',
               total_td='31',	pass_yards='3443',	rush_yards='1257',	int_for='12',	forced_fumbles='10',	fumbles_recovered='9',	sacks='52',	fumble_td='2',	int_td='3',	safeties='2')
    det = Team(team_name='Detroit Lions',	conference='NFC',	division='North',	wins='3',	losses='12',	ties='1',	points_for='341',	points_against='423',	rush_td='7',	pass_td='28',
               total_td='38',	pass_yards='4187',	rush_yards='1649',	int_for='7',	forced_fumbles='16',	fumbles_recovered='11',	sacks='43',	fumble_td='1',	int_td='0',	safeties='0')
    gb = Team(team_name='Green Bay Packers',	conference='NFC',	division='North',	wins='13',	losses='3',	ties='0',	points_for='376',	points_against='313',	rush_td='18',	pass_td='26',
              total_td='44',	pass_yards='4017',	rush_yards='1795',	int_for='17',	forced_fumbles='12',	fumbles_recovered='7',	sacks='36',	fumble_td='0',	int_td='0',	safeties='0')
    car = Team(team_name='Carolina Panthers',	conference='NFC',	division='South',	wins='5',	losses='11',	ties='0',	points_for='340',	points_against='470',	rush_td='20',	pass_td='17',
               total_td='38',	pass_yards='4134',	rush_yards='1819',	int_for='14',	forced_fumbles='8',	fumbles_recovered='7',	sacks='58',	fumble_td='1',	int_td='0',	safeties='2')
    ne = Team(team_name='New England Patriots',	conference='AFC',	division='East',	wins='12',	losses='4',	ties='0',	points_for='420',	points_against='225',	rush_td='17',	pass_td='25',
              total_td='49',	pass_yards='4153',	rush_yards='1703',	int_for='25',	forced_fumbles='15',	fumbles_recovered='11',	sacks='28',	fumble_td='2',	int_td='3',	safeties='1')
    oak = Team(team_name='Oakland Raiders',	conference='AFC',	division='West',	wins='7',	losses='9',	ties='0',	points_for='313',	points_against='419',	rush_td='13',	pass_td='22',
               total_td='37',	pass_yards='4110',	rush_yards='1893',	int_for='9',	forced_fumbles='9',	fumbles_recovered='6',	sacks='29',	fumble_td='0',	int_td='2',	safeties='0')
    lar = Team(team_name='Los Angeles Rams',	conference='NFC',	division='West',	wins='9',	losses='7',	ties='0',	points_for='394',	points_against='364',	rush_td='20',	pass_td='22',
               total_td='46',	pass_yards='4669',	rush_yards='1499',	int_for='13',	forced_fumbles='15',	fumbles_recovered='11',	sacks='22',	fumble_td='2',	int_td='2',	safeties='1')
    bal = Team(team_name='Baltimore Ravens',	conference='AFC',	division='North',	wins='14',	losses='2',	ties='0',	points_for='531',	points_against='282',	rush_td='21',	pass_td='37',
               total_td='64',	pass_yards='3350',	rush_yards='3296',	int_for='13',	forced_fumbles='15',	fumbles_recovered='12',	sacks='28',	fumble_td='4',	int_td='2',	safeties='1')
    was = Team(team_name='Washington Redskins',	conference='NFC',	division='East',	wins='3',	losses='13',	ties='0',	points_for='266',	points_against='435',	rush_td='9',	pass_td='18',
               total_td='28',	pass_yards='3205',	rush_yards='1583',	int_for='13',	forced_fumbles='16',	fumbles_recovered='9',	sacks='50',	fumble_td='0',	int_td='0',	safeties='0')
    no = Team(team_name='New Orleans Saints',	conference='NFC',	division='South',	wins='13',	losses='3',	ties='0',	points_for='458',	points_against='341',	rush_td='12',	pass_td='36',
              total_td='52',	pass_yards='4431',	rush_yards='1738',	int_for='13',	forced_fumbles='11',	fumbles_recovered='10',	sacks='25',	fumble_td='1',	int_td='2',	safeties='1')
    sea = Team(team_name='Seattle Seahawks',	conference='NFC',	division='West',	wins='11',	losses='5',	ties='0',	points_for='405',	points_against='398',	rush_td='15',	pass_td='31',
               total_td='49',	pass_yards='4110',	rush_yards='2200',	int_for='16',	forced_fumbles='19',	fumbles_recovered='16',	sacks='48',	fumble_td='1',	int_td='2',	safeties='0')
    pit = Team(team_name='Pittsburgh Steelers',	conference='AFC',	division='North',	wins='8',	losses='8',	ties='0',	points_for='289',	points_against='303',	rush_td='7',	pass_td='18',
               total_td='29',	pass_yards='3214',	rush_yards='1447',	int_for='20',	forced_fumbles='22',	fumbles_recovered='18',	sacks='32',	fumble_td='2',	int_td='1',	safeties='0')
    hou = Team(team_name='Houston Texans',	conference='AFC',	division='South',	wins='10',	losses='6',	ties='0',	points_for='378',	points_against='385',	rush_td='17',	pass_td='27',
               total_td='46',	pass_yards='4083',	rush_yards='2009',	int_for='12',	forced_fumbles='14',	fumbles_recovered='10',	sacks='49',	fumble_td='0',	int_td='2',	safeties='0')
    ten = Team(team_name='Tennessee Titans',	conference='AFC',	division='South',	wins='9',	losses='7',	ties='0',	points_for='402',	points_against='331',	rush_td='21',	pass_td='29',
               total_td='54',	pass_yards='3956',	rush_yards='2223',	int_for='14',	forced_fumbles='11',	fumbles_recovered='9',	sacks='56',	fumble_td='2',	int_td='1',	safeties='1')
    minn = Team(team_name='Minnesota Vikings',	conference='NFC',	division='North',	wins='10',	losses='6',	ties='0',	points_for='407',	points_against='303',	rush_td='19',	pass_td='26',
                total_td='47',	pass_yards='3729',	rush_yards='2133',	int_for='17',	forced_fumbles='19',	fumbles_recovered='14',	sacks='28',	fumble_td='1',	int_td='1',	safeties='1')
    sf.save()
    chi.save()
    cin.save()
    buf.save()
    den.save()
    cle.save()
    tb.save()
    ari.save()
    lac.save()
    kc.save()
    ind.save()
    dal.save()
    mia.save()
    phi.save()
    atl.save()
    nyg.save()
    jax.save()
    nyj.save()
    det.save()
    gb.save()
    car.save()
    ne.save()
    oak.save()
    lar.save()
    bal.save()
    was.save()
    no.save()
    sea.save()
    pit.save()
    hou.save()
    ten.save()
    minn.save()

    Game(game_id='1',	week='1',	day='Thursday',	date='43713',	away_team=gb,	away_spread='4',
         home_team=chi,	home_spread='-4',	over_under='45.5',	away_score='10',	home_score='3').save()

    Game(game_id='2',	week='1',	day='Sunday',	date='43716',	away_team=buf,	away_spread='3.5',
         home_team=nyj,	home_spread='-3.5',	over_under='38.5',	away_score='17',	home_score='16').save()
    Game(game_id='3',	week='1',	day='Sunday',	date='43716',	away_team=ten,	away_spread='5',
         home_team=cle,	home_spread='-5',	over_under='45',	away_score='43',	home_score='13').save()
    Game(game_id='4',	week='1',	day='Sunday',	date='43716',	away_team=bal,	away_spread='-4',
         home_team=mia,	home_spread='4',	over_under='37',	away_score='59',	home_score='10').save()
    Game(game_id='5',	week='1',	day='Sunday',	date='43716',	away_team=atl,	away_spread='4',
         home_team=minn,	home_spread='-4',	over_under='47.5',	away_score='12',	home_score='28').save()
    Game(game_id='6',	week='1',	day='Sunday',	date='43716',	away_team=was,	away_spread='9',
         home_team=phi,	home_spread='-9',	over_under='46.5',	away_score='27',	home_score='32').save()
    Game(game_id='7',	week='1',	day='Sunday',	date='43716',	away_team=lar,	away_spread='-2.5',
         home_team=car,	home_spread='2.5',	over_under='51',	away_score='30',	home_score='27').save()
    Game(game_id='8',	week='1',	day='Sunday',	date='43716',	away_team=kc,	away_spread='-4',
         home_team=jax,	home_spread='4',	over_under='52',	away_score='40',	home_score='26').save()
    Game(game_id='9',	week='1',	day='Sunday',	date='43716',	away_team=ind,	away_spread='3',
         home_team=lac,	home_spread='-3',	over_under='48.5',	away_score='24',	home_score='30').save()
    Game(game_id='10',	week='1',	day='Sunday',	date='43716',	away_team=cin,	away_spread='9',
         home_team=sea,	home_spread='-9',	over_under='43.5',	away_score='20',	home_score='21').save()
    Game(game_id='11',	week='1',	day='Sunday',	date='43716',	away_team=nyg,	away_spread='7',
         home_team=dal,	home_spread='-7',	over_under='46.5',	away_score='17',	home_score='35').save()
    Game(game_id='12',	week='1',	day='Sunday',	date='43716',	away_team=det,	away_spread='0',
         home_team=ari,	home_spread='0',	over_under='48.5',	away_score='27',	home_score='27').save()
    Game(game_id='13',	week='1',	day='Sunday',	date='43716',	away_team=sf,	away_spread='1',
         home_team=tb,	home_spread='-1',	over_under='49',	away_score='31',	home_score='17').save()
    Game(game_id='14',	week='1',	day='Sunday',	date='43716',	away_team=pit,	away_spread='6.5',
         home_team=ne,	home_spread='-6.5',	over_under='52',	away_score='3',	home_score='33').save()
    Game(game_id='15',	week='1',	day='Monday',	date='43717',	away_team=hou,	away_spread='7',
         home_team=no,	home_spread='-7',	over_under='53.5',	away_score='28',	home_score='30').save()
    Game(game_id='16',	week='1',	day='Monday',	date='43717',	away_team=den,	away_spread='2.5',
         home_team=oak,	home_spread='-2.5',	over_under='43',	away_score='16',	home_score='24').save()
    Game(game_id='17',	week='2',	day='Thursday',	date='43720',	away_team=tb,	away_spread='6.5',
         home_team=car,	home_spread='-6.5',	over_under='50.5',	away_score='20',	home_score='14').save()
    Game(game_id='18',	week='2',	day='Sunday',	date='43723',	away_team=sf,	away_spread='-1.5',
         home_team=cin,	home_spread='1.5',	over_under='45',	away_score='41',	home_score='17').save()
    Game(game_id='19',	week='2',	day='Sunday',	date='43723',	away_team=lac,	away_spread='-3',
         home_team=det,	home_spread='3',	over_under='47',	away_score='10',	home_score='13').save()
    Game(game_id='20',	week='2',	day='Sunday',	date='43723',	away_team=minn,	away_spread='2.5',
         home_team=gb,	home_spread='-2.5',	over_under='46',	away_score='16',	home_score='21').save()
    Game(game_id='21',	week='2',	day='Sunday',	date='43723',	away_team=ind,	away_spread='3',
         home_team=ten,	home_spread='-3',	over_under='44',	away_score='19',	home_score='17').save()
    Game(game_id='22',	week='2',	day='Sunday',	date='43723',	away_team=ne,	away_spread='-15',
         home_team=mia,	home_spread='15',	over_under='47',	away_score='43',	home_score='0').save()
    Game(game_id='23',	week='2',	day='Sunday',	date='43723',	away_team=buf,	away_spread='-2.5',
         home_team=nyg,	home_spread='2.5',	over_under='42.5',	away_score='28',	home_score='14').save()
    Game(game_id='24',	week='2',	day='Sunday',	date='43723',	away_team=sea,	away_spread='3.5',
         home_team=pit,	home_spread='-3.5',	over_under='46.5',	away_score='28',	home_score='26').save()
    Game(game_id='25',	week='2',	day='Sunday',	date='43723',	away_team=dal,	away_spread='-6.5',
         home_team=was,	home_spread='6.5',	over_under='44',	away_score='31',	home_score='21').save()
    Game(game_id='26',	week='2',	day='Sunday',	date='43723',	away_team=ari,	away_spread='14',
         home_team=bal,	home_spread='-14',	over_under='42.5',	away_score='17',	home_score='23').save()
    Game(game_id='27',	week='2',	day='Sunday',	date='43723',	away_team=jax,	away_spread='8.5',
         home_team=hou,	home_spread='-8.5',	over_under='44.5',	away_score='12',	home_score='13').save()
    Game(game_id='28',	week='2',	day='Sunday',	date='43723',	away_team=kc,	away_spread='-7.5',
         home_team=oak,	home_spread='7.5',	over_under='52',	away_score='28',	home_score='10').save()
    Game(game_id='29',	week='2',	day='Sunday',	date='43723',	away_team=chi,	away_spread='1',
         home_team=den,	home_spread='-1',	over_under='40.5',	away_score='16',	home_score='14').save()
    Game(game_id='30',	week='2',	day='Sunday',	date='43723',	away_team=no,	away_spread='3',
         home_team=lar,	home_spread='-3',	over_under='54',	away_score='9',	home_score='27').save()
    Game(game_id='31',	week='2',	day='Sunday',	date='43723',	away_team=phi,	away_spread='-1',
         home_team=atl,	home_spread='1',	over_under='51',	away_score='20',	home_score='24').save()
    Game(game_id='32',	week='2',	day='Monday',	date='43724',	away_team=cle,	away_spread='-1',
         home_team=nyj,	home_spread='1',	over_under='46',	away_score='23',	home_score='3').save()
    Game(game_id='33',	week='3',	day='Thursday',	date='43727',	away_team=ten,	away_spread='-1.5',
         home_team=jax,	home_spread='1.5',	over_under='40',	away_score='7',	home_score='20').save()
    Game(game_id='34',	week='3',	day='Sunday',	date='43730',	away_team=atl,	away_spread='2.5',
         home_team=ind,	home_spread='-2.5',	over_under='47.5',	away_score='24',	home_score='27').save()
    Game(game_id='35',	week='3',	day='Sunday',	date='43730',	away_team=bal,	away_spread='6.5',
         home_team=kc,	home_spread='-6.5',	over_under='53.5',	away_score='28',	home_score='33').save()
    Game(game_id='36',	week='3',	day='Sunday',	date='43730',	away_team=cin,	away_spread='5',
         home_team=buf,	home_spread='-5',	over_under='42',	away_score='17',	home_score='21').save()
    Game(game_id='37',	week='3',	day='Sunday',	date='43730',	away_team=den,	away_spread='8',
         home_team=gb,	home_spread='-8',	over_under='43.5',	away_score='16',	home_score='27').save()
    Game(game_id='38',	week='3',	day='Sunday',	date='43730',	away_team=det,	away_spread='8',
         home_team=phi,	home_spread='-8',	over_under='48.5',	away_score='27',	home_score='24').save()
    Game(game_id='39',	week='3',	day='Sunday',	date='43730',	away_team=mia,	away_spread='21',
         home_team=dal,	home_spread='-21',	over_under='47.5',	away_score='6',	home_score='31').save()
    Game(game_id='40',	week='3',	day='Sunday',	date='43730',	away_team=nyj,	away_spread='20',
         home_team=ne,	home_spread='-20',	over_under='46',	away_score='14',	home_score='30').save()
    Game(game_id='41',	week='3',	day='Sunday',	date='43730',	away_team=oak,	away_spread='7.5',
         home_team=minn,	home_spread='-7.5',	over_under='43.5',	away_score='14',	home_score='34').save()
    Game(game_id='42',	week='3',	day='Sunday',	date='43730',	away_team=car,	away_spread='-2.5',
         home_team=ari,	home_spread='2.5',	over_under='35.5',	away_score='38',	home_score='20').save()
    Game(game_id='43',	week='3',	day='Sunday',	date='43730',	away_team=nyg,	away_spread='6.5',
         home_team=tb,	home_spread='-6.5',	over_under='48',	away_score='32',	home_score='31').save()
    Game(game_id='44',	week='3',	day='Sunday',	date='43730',	away_team=hou,	away_spread='3',
         home_team=lac,	home_spread='-3',	over_under='48',	away_score='27',	home_score='20').save()
    Game(game_id='45',	week='3',	day='Sunday',	date='43730',	away_team=no,	away_spread='5.5',
         home_team=sea,	home_spread='-5.5',	over_under='44.5',	away_score='33',	home_score='27').save()
    Game(game_id='46',	week='3',	day='Sunday',	date='43730',	away_team=pit,	away_spread='7.5',
         home_team=sf,	home_spread='-7.5',	over_under='43.5',	away_score='20',	home_score='24').save()
    Game(game_id='47',	week='3',	day='Sunday',	date='43730',	away_team=lar,	away_spread='-1',
         home_team=cle,	home_spread='1',	over_under='51',	away_score='20',	home_score='13').save()
    Game(game_id='48',	week='3',	day='Monday',	date='43731',	away_team=chi,	away_spread='-4.5',
         home_team=was,	home_spread='4.5',	over_under='42',	away_score='31',	home_score='15').save()
    Game(game_id='49',	week='4',	day='Thursday',	date='43734',	away_team=phi,	away_spread='3.5',
         home_team=gb,	home_spread='-3.5',	over_under='47.5',	away_score='34',	home_score='27').save()
    Game(game_id='50',	week='4',	day='Sunday',	date='43737',	away_team=car,	away_spread='5',
         home_team=hou,	home_spread='-5',	over_under='46',	away_score='16',	home_score='10').save()
    Game(game_id='51',	week='4',	day='Sunday',	date='43737',	away_team=cle,	away_spread='6',
         home_team=bal,	home_spread='-6',	over_under='46',	away_score='40',	home_score='25').save()
    Game(game_id='52',	week='4',	day='Sunday',	date='43737',	away_team=kc,	away_spread='-6.5',
         home_team=det,	home_spread='6.5',	over_under='53.5',	away_score='34',	home_score='30').save()
    Game(game_id='53',	week='4',	day='Sunday',	date='43737',	away_team=lac,	away_spread='-16.5',
         home_team=mia,	home_spread='16.5',	over_under='44.5',	away_score='30',	home_score='10').save()
    Game(game_id='54',	week='4',	day='Sunday',	date='43737',	away_team=ne,	away_spread='-7.5',
         home_team=buf,	home_spread='7.5',	over_under='43.5',	away_score='16',	home_score='10').save()
    Game(game_id='55',	week='4',	day='Sunday',	date='43737',	away_team=oak,	away_spread='7',
         home_team=ind,	home_spread='-7',	over_under='44.5',	away_score='31',	home_score='24').save()
    Game(game_id='56',	week='4',	day='Sunday',	date='43737',	away_team=ten,	away_spread='5',
         home_team=atl,	home_spread='-5',	over_under='46',	away_score='24',	home_score='10').save()
    Game(game_id='57',	week='4',	day='Sunday',	date='43737',	away_team=was,	away_spread='2.5',
         home_team=nyg,	home_spread='-2.5',	over_under='46.5',	away_score='3',	home_score='24').save()
    Game(game_id='58',	week='4',	day='Sunday',	date='43737',	away_team=sea,	away_spread='-4',
         home_team=ari,	home_spread='4',	over_under='47',	away_score='27',	home_score='10').save()
    Game(game_id='59',	week='4',	day='Sunday',	date='43737',	away_team=tb,	away_spread='10.5',
         home_team=lar,	home_spread='-10.5',	over_under='50.5',	away_score='55',	home_score='40').save()
    Game(game_id='60',	week='4',	day='Sunday',	date='43737',	away_team=jax,	away_spread='3',
         home_team=den,	home_spread='-3',	over_under='37.5',	away_score='26',	home_score='24').save()
    Game(game_id='61',	week='4',	day='Sunday',	date='43737',	away_team=minn,	away_spread='3',
         home_team=chi,	home_spread='-3',	over_under='38',	away_score='6',	home_score='16').save()
    Game(game_id='62',	week='4',	day='Sunday',	date='43737',	away_team=dal,	away_spread='-3.5',
         home_team=no,	home_spread='3.5',	over_under='45.5',	away_score='10',	home_score='12').save()
    Game(game_id='63',	week='4',	day='Monday',	date='43738',	away_team=cin,	away_spread='4.5',
         home_team=pit,	home_spread='-4.5',	over_under='43.5',	away_score='3',	home_score='27').save()
    Game(game_id='64',	week='5',	day='Thursday',	date='43741',	away_team=lar,	away_spread='-1.5',
         home_team=sea,	home_spread='1.5',	over_under='49',	away_score='29',	home_score='30').save()
    Game(game_id='65',	week='5',	day='Sunday',	date='43744',	away_team=ari,	away_spread='4',
         home_team=cin,	home_spread='-4',	over_under='48',	away_score='26',	home_score='23').save()
    Game(game_id='66',	week='5',	day='Sunday',	date='43744',	away_team=atl,	away_spread='5',
         home_team=hou,	home_spread='-5',	over_under='49',	away_score='32',	home_score='53').save()
    Game(game_id='67',	week='5',	day='Sunday',	date='43744',	away_team=bal,	away_spread='-4',
         home_team=pit,	home_spread='4',	over_under='42.5',	away_score='26',	home_score='23').save()
    Game(game_id='68',	week='5',	day='Sunday',	date='43744',	away_team=buf,	away_spread='2.5',
         home_team=ten,	home_spread='-2.5',	over_under='38.5',	away_score='14',	home_score='7').save()
    Game(game_id='69',	week='5',	day='Sunday',	date='43744',	away_team=chi,	away_spread='-4.5',
         home_team=oak,	home_spread='4.5',	over_under='41.5',	away_score='21',	home_score='24').save()
    Game(game_id='70',	week='5',	day='Sunday',	date='43744',	away_team=jax,	away_spread='3',
         home_team=car,	home_spread='-3',	over_under='41',	away_score='27',	home_score='34').save()
    Game(game_id='71',	week='5',	day='Sunday',	date='43744',	away_team=minn,	away_spread='-5',
         home_team=nyg,	home_spread='5',	over_under='44.5',	away_score='28',	home_score='10').save()
    Game(game_id='72',	week='5',	day='Sunday',	date='43744',	away_team=ne,	away_spread='-14',
         home_team=was,	home_spread='14',	over_under='45.5',	away_score='33',	home_score='7').save()
    Game(game_id='73',	week='5',	day='Sunday',	date='43744',	away_team=nyj,	away_spread='14',
         home_team=phi,	home_spread='-14',	over_under='44.5',	away_score='6',	home_score='31').save()
    Game(game_id='74',	week='5',	day='Sunday',	date='43744',	away_team=tb,	away_spread='4.5',
         home_team=no,	home_spread='-4.5',	over_under='47.5',	away_score='24',	home_score='31').save()
    Game(game_id='75',	week='5',	day='Sunday',	date='43744',	away_team=den,	away_spread='6.5',
         home_team=lac,	home_spread='-6.5',	over_under='44',	away_score='20',	home_score='13').save()
    Game(game_id='76',	week='5',	day='Sunday',	date='43744',	away_team=gb,	away_spread='3.5',
         home_team=dal,	home_spread='-3.5',	over_under='47',	away_score='34',	home_score='24').save()
    Game(game_id='77',	week='5',	day='Sunday',	date='43744',	away_team=ind,	away_spread='9.5',
         home_team=kc,	home_spread='-9.5',	over_under='57',	away_score='19',	home_score='13').save()
    Game(game_id='78',	week='5',	day='Monday',	date='43745',	away_team=cle,	away_spread='3',
         home_team=sf,	home_spread='-3',	over_under='47.5',	away_score='3',	home_score='31').save()
    Game(game_id='79',	week='6',	day='Thursday',	date='43748',	away_team=nyg,	away_spread='15.5',
         home_team=ne,	home_spread='-15.5',	over_under='46',	away_score='14',	home_score='35').save()
    Game(game_id='80',	week='6',	day='Sunday',	date='43751',	away_team=car,	away_spread='1',
         home_team=tb,	home_spread='-1',	over_under='46',	away_score='37',	home_score='26').save()
    Game(game_id='81',	week='6',	day='Sunday',	date='43751',	away_team=cin,	away_spread='10.5',
         home_team=bal,	home_spread='-10.5',	over_under='47.5',	away_score='17',	home_score='23').save()
    Game(game_id='82',	week='6',	day='Sunday',	date='43751',	away_team=hou,	away_spread='6.5',
         home_team=kc,	home_spread='-6.5',	over_under='55.5',	away_score='31',	home_score='24').save()
    Game(game_id='83',	week='6',	day='Sunday',	date='43751',	away_team=no,	away_spread='-2',
         home_team=jax,	home_spread='2',	over_under='44',	away_score='13',	home_score='6').save()
    Game(game_id='84',	week='6',	day='Sunday',	date='43751',	away_team=phi,	away_spread='3',
         home_team=minn,	home_spread='-3',	over_under='44',	away_score='20',	home_score='38').save()
    Game(game_id='85',	week='6',	day='Sunday',	date='43751',	away_team=sea,	away_spread='-1',
         home_team=cle,	home_spread='1',	over_under='47.5',	away_score='32',	home_score='28').save()
    Game(game_id='86',	week='6',	day='Sunday',	date='43751',	away_team=was,	away_spread='-4.5',
         home_team=mia,	home_spread='4.5',	over_under='41',	away_score='17',	home_score='16').save()
    Game(game_id='87',	week='6',	day='Sunday',	date='43751',	away_team=atl,	away_spread='-2.5',
         home_team=ari,	home_spread='2.5',	over_under='49.5',	away_score='33',	home_score='34').save()
    Game(game_id='88',	week='6',	day='Sunday',	date='43751',	away_team=sf,	away_spread='3',
         home_team=lar,	home_spread='-3',	over_under='48.5',	away_score='20',	home_score='7').save()
    Game(game_id='89',	week='6',	day='Sunday',	date='43751',	away_team=dal,	away_spread='-7.5',
         home_team=nyj,	home_spread='7.5',	over_under='43.5',	away_score='22',	home_score='24').save()
    Game(game_id='90',	week='6',	day='Sunday',	date='43751',	away_team=ten,	away_spread='2.5',
         home_team=den,	home_spread='-2.5',	over_under='40',	away_score='0',	home_score='16').save()
    Game(game_id='91',	week='6',	day='Sunday',	date='43751',	away_team=pit,	away_spread='6',
         home_team=lac,	home_spread='-6',	over_under='41.5',	away_score='24',	home_score='27').save()
    Game(game_id='92',	week='6',	day='Monday',	date='43752',	away_team=det,	away_spread='6',
         home_team=gb,	home_spread='-6',	over_under='47',	away_score='22',	home_score='23').save()
    Game(game_id='93',	week='7',	day='Thursday',	date='43755',	away_team=kc,	away_spread='-3.5',
         home_team=den,	home_spread='3.5',	over_under='49',	away_score='30',	home_score='6').save()
    Game(game_id='94',	week='7',	day='Sunday',	date='43758',	away_team=ari,	away_spread='3',
         home_team=nyg,	home_spread='-3',	over_under='49.5',	away_score='27',	home_score='21').save()
    Game(game_id='95',	week='7',	day='Sunday',	date='43758',	away_team=hou,	away_spread='1',
         home_team=ind,	home_spread='-1',	over_under='48',	away_score='23',	home_score='30').save()
    Game(game_id='96',	week='7',	day='Sunday',	date='43758',	away_team=jax,	away_spread='-3',
         home_team=cin,	home_spread='3',	over_under='43.5',	away_score='27',	home_score='17').save()
    Game(game_id='97',	week='7',	day='Sunday',	date='43758',	away_team=lar,	away_spread='-3',
         home_team=atl,	home_spread='3',	over_under='53.5',	away_score='37',	home_score='10').save()
    Game(game_id='98',	week='7',	day='Sunday',	date='43758',	away_team=mia,	away_spread='16',
         home_team=buf,	home_spread='-16',	over_under='39.5',	away_score='21',	home_score='31').save()
    Game(game_id='99',	week='7',	day='Sunday',	date='43758',	away_team=minn,	away_spread='2',
         home_team=det,	home_spread='-2',	over_under='44',	away_score='42',	home_score='30').save()
    Game(game_id='100',	week='7',	day='Sunday',	date='43758',	away_team=oak,	away_spread='6.5',
         home_team=gb,	home_spread='-6.5',	over_under='46.5',	away_score='24',	home_score='42').save()
    Game(game_id='101',	week='7',	day='Sunday',	date='43758',	away_team=sf,	away_spread='-9.5',
         home_team=was,	home_spread='9.5',	over_under='42.5',	away_score='9',	home_score='0').save()
    Game(game_id='102',	week='7',	day='Sunday',	date='43758',	away_team=lac,	away_spread='1',
         home_team=ten,	home_spread='-1',	over_under='38.5',	away_score='20',	home_score='23').save()
    Game(game_id='103',	week='7',	day='Sunday',	date='43758',	away_team=bal,	away_spread='4',
         home_team=sea,	home_spread='-4',	over_under='50.5',	away_score='30',	home_score='16').save()
    Game(game_id='104',	week='7',	day='Sunday',	date='43758',	away_team=no,	away_spread='4',
         home_team=chi,	home_spread='-4',	over_under='39.5',	away_score='36',	home_score='25').save()
    Game(game_id='105',	week='7',	day='Sunday',	date='43758',	away_team=phi,	away_spread='3',
         home_team=dal,	home_spread='-3',	over_under='48.5',	away_score='10',	home_score='37').save()
    Game(game_id='106',	week='7',	day='Monday',	date='43759',	away_team=ne,	away_spread='-10',
         home_team=nyj,	home_spread='10',	over_under='42.5',	away_score='33',	home_score='0').save()
    Game(game_id='107',	week='8',	day='Thursday',	date='43762',	away_team=was,	away_spread='16',
         home_team=minn,	home_spread='-16',	over_under='41',	away_score='9',	home_score='19').save()
    Game(game_id='108',	week='8',	day='Sunday',	date='43765',	away_team=ari,	away_spread='10.5',
         home_team=no,	home_spread='-10.5',	over_under='49.5',	away_score='9',	home_score='31').save()
    Game(game_id='109',	week='8',	day='Sunday',	date='43765',	away_team=cin,	away_spread='12.5',
         home_team=lar,	home_spread='-12.5',	over_under='48',	away_score='10',	home_score='24').save()
    Game(game_id='110',	week='8',	day='Sunday',	date='43765',	away_team=lac,	away_spread='5',
         home_team=chi,	home_spread='-5',	over_under='40',	away_score='17',	home_score='16').save()
    Game(game_id='111',	week='8',	day='Sunday',	date='43765',	away_team=nyg,	away_spread='7',
         home_team=det,	home_spread='-7',	over_under='48.5',	away_score='26',	home_score='31').save()
    Game(game_id='112',	week='8',	day='Sunday',	date='43765',	away_team=nyj,	away_spread='5',
         home_team=jax,	home_spread='-5',	over_under='40.5',	away_score='15',	home_score='29').save()
    Game(game_id='113',	week='8',	day='Sunday',	date='43765',	away_team=oak,	away_spread='6.5',
         home_team=hou,	home_spread='-6.5',	over_under='50.5',	away_score='24',	home_score='27').save()
    Game(game_id='114',	week='8',	day='Sunday',	date='43765',	away_team=phi,	away_spread='1',
         home_team=buf,	home_spread='-1',	over_under='43.5',	away_score='31',	home_score='13').save()
    Game(game_id='115',	week='8',	day='Sunday',	date='43765',	away_team=sea,	away_spread='-7.5',
         home_team=atl,	home_spread='7.5',	over_under='51',	away_score='27',	home_score='20').save()
    Game(game_id='116',	week='8',	day='Sunday',	date='43765',	away_team=tb,	away_spread='2.5',
         home_team=ten,	home_spread='-2.5',	over_under='46.5',	away_score='23',	home_score='27').save()
    Game(game_id='117',	week='8',	day='Sunday',	date='43765',	away_team=car,	away_spread='6',
         home_team=sf,	home_spread='-6',	over_under='42',	away_score='13',	home_score='51').save()
    Game(game_id='118',	week='8',	day='Sunday',	date='43765',	away_team=cle,	away_spread='10.5',
         home_team=ne,	home_spread='-10.5',	over_under='46',	away_score='13',	home_score='27').save()
    Game(game_id='119',	week='8',	day='Sunday',	date='43765',	away_team=den,	away_spread='6',
         home_team=ind,	home_spread='-6',	over_under='43.5',	away_score='13',	home_score='15').save()
    Game(game_id='120',	week='8',	day='Sunday',	date='43765',	away_team=gb,	away_spread='-3',
         home_team=kc,	home_spread='3',	over_under='48',	away_score='31',	home_score='24').save()
    Game(game_id='121',	week='8',	day='Monday',	date='43766',	away_team=mia,	away_spread='14.5',
         home_team=pit,	home_spread='-14.5',	over_under='43',	away_score='14',	home_score='27').save()
    Game(game_id='122',	week='9',	day='Thursday',	date='43769',	away_team=sf,	away_spread='-8',
         home_team=ari,	home_spread='8',	over_under='44',	away_score='28',	home_score='25').save()
    Game(game_id='123',	week='9',	day='Sunday',	date='43772',	away_team=hou,	away_spread='-2.5',
         home_team=jax,	home_spread='2.5',	over_under='47',	away_score='26',	home_score='3').save()
    Game(game_id='124',	week='9',	day='Sunday',	date='43772',	away_team=chi,	away_spread='5',
         home_team=phi,	home_spread='-5',	over_under='44',	away_score='14',	home_score='22').save()
    Game(game_id='125',	week='9',	day='Sunday',	date='43772',	away_team=ind,	away_spread='1.5',
         home_team=pit,	home_spread='-1.5',	over_under='43',	away_score='24',	home_score='26').save()
    Game(game_id='126',	week='9',	day='Sunday',	date='43772',	away_team=minn,	away_spread='-3.5',
         home_team=kc,	home_spread='3.5',	over_under='46.5',	away_score='23',	home_score='26').save()
    Game(game_id='127',	week='9',	day='Sunday',	date='43772',	away_team=nyj,	away_spread='-3',
         home_team=mia,	home_spread='3',	over_under='40',	away_score='18',	home_score='26').save()
    Game(game_id='128',	week='9',	day='Sunday',	date='43772',	away_team=ten,	away_spread='3.5',
         home_team=car,	home_spread='-3.5',	over_under='41',	away_score='20',	home_score='30').save()
    Game(game_id='129',	week='9',	day='Sunday',	date='43772',	away_team=was,	away_spread='10.5',
         home_team=buf,	home_spread='-10.5',	over_under='37',	away_score='9',	home_score='24').save()
    Game(game_id='130',	week='9',	day='Sunday',	date='43772',	away_team=det,	away_spread='2',
         home_team=oak,	home_spread='-2',	over_under='51.5',	away_score='24',	home_score='31').save()
    Game(game_id='131',	week='9',	day='Sunday',	date='43772',	away_team=tb,	away_spread='6.5',
         home_team=sea,	home_spread='-6.5',	over_under='53',	away_score='34',	home_score='40').save()
    Game(game_id='132',	week='9',	day='Sunday',	date='43772',	away_team=cle,	away_spread='1.5',
         home_team=den,	home_spread='-1.5',	over_under='43',	away_score='19',	home_score='24').save()
    Game(game_id='133',	week='9',	day='Sunday',	date='43772',	away_team=gb,	away_spread='-3',
         home_team=lac,	home_spread='3',	over_under='46',	away_score='11',	home_score='26').save()
    Game(game_id='134',	week='9',	day='Sunday',	date='43772',	away_team=ne,	away_spread='-4',
         home_team=bal,	home_spread='4',	over_under='45',	away_score='20',	home_score='37').save()
    Game(game_id='135',	week='9',	day='Monday',	date='43773',	away_team=dal,	away_spread='-7.5',
         home_team=nyg,	home_spread='7.5',	over_under='48',	away_score='37',	home_score='18').save()
    Game(game_id='136',	week='10',	day='Thursday',	date='43776',	away_team=lac,	away_spread='1.5',
         home_team=oak,	home_spread='-1.5',	over_under='47.5',	away_score='24',	home_score='26').save()
    Game(game_id='137',	week='10',	day='Sunday',	date='43779',	away_team=ari,	away_spread='6',
         home_team=tb,	home_spread='-6',	over_under='54',	away_score='27',	home_score='30').save()
    Game(game_id='138',	week='10',	day='Sunday',	date='43779',	away_team=atl,	away_spread='12',
         home_team=no,	home_spread='-12',	over_under='51',	away_score='26',	home_score='9').save()
    Game(game_id='139',	week='10',	day='Sunday',	date='43779',	away_team=bal,	away_spread='-10.5',
         home_team=cin,	home_spread='10.5',	over_under='46.5',	away_score='49',	home_score='13').save()
    Game(game_id='140',	week='10',	day='Sunday',	date='43779',	away_team=buf,	away_spread='2.5',
         home_team=cle,	home_spread='-2.5',	over_under='41.5',	away_score='16',	home_score='19').save()
    Game(game_id='141',	week='10',	day='Sunday',	date='43779',	away_team=car,	away_spread='6',
         home_team=gb,	home_spread='-6',	over_under='48',	away_score='16',	home_score='24').save()
    Game(game_id='142',	week='10',	day='Sunday',	date='43779',	away_team=det,	away_spread='3',
         home_team=chi,	home_spread='-3',	over_under='44',	away_score='13',	home_score='20').save()
    Game(game_id='143',	week='10',	day='Sunday',	date='43779',	away_team=kc,	away_spread='-6',
         home_team=ten,	home_spread='6',	over_under='48',	away_score='32',	home_score='35').save()
    Game(game_id='144',	week='10',	day='Sunday',	date='43779',	away_team=nyg,	away_spread='-3',
         home_team=nyj,	home_spread='3',	over_under='43.5',	away_score='27',	home_score='34').save()
    Game(game_id='145',	week='10',	day='Sunday',	date='43779',	away_team=mia,	away_spread='11.5',
         home_team=ind,	home_spread='-11.5',	over_under='42.5',	away_score='16',	home_score='12').save()
    Game(game_id='146',	week='10',	day='Sunday',	date='43779',	away_team=lar,	away_spread='-4',
         home_team=pit,	home_spread='4',	over_under='45',	away_score='12',	home_score='17').save()
    Game(game_id='147',	week='10',	day='Sunday',	date='43779',	away_team=minn,	away_spread='3',
         home_team=dal,	home_spread='-3',	over_under='48',	away_score='28',	home_score='24').save()
    Game(game_id='148',	week='10',	day='Monday',	date='43780',	away_team=sea,	away_spread='6.5',
         home_team=sf,	home_spread='-6.5',	over_under='44.5',	away_score='27',	home_score='24').save()
    Game(game_id='149',	week='11',	day='Thursday',	date='43783',	away_team=pit,	away_spread='3',
         home_team=cle,	home_spread='-3',	over_under='40.5',	away_score='7',	home_score='21').save()
    Game(game_id='150',	week='11',	day='Sunday',	date='43786',	away_team=atl,	away_spread='6.5',
         home_team=car,	home_spread='-6.5',	over_under='50.5',	away_score='29',	home_score='3').save()
    Game(game_id='151',	week='11',	day='Sunday',	date='43786',	away_team=buf,	away_spread='-6.5',
         home_team=mia,	home_spread='6.5',	over_under='39',	away_score='37',	home_score='20').save()
    Game(game_id='152',	week='11',	day='Sunday',	date='43786',	away_team=dal,	away_spread='-7',
         home_team=det,	home_spread='7',	over_under='46.5',	away_score='35',	home_score='27').save()
    Game(game_id='153',	week='11',	day='Sunday',	date='43786',	away_team=den,	away_spread='10.5',
         home_team=minn,	home_spread='-10.5',	over_under='39.5',	away_score='23',	home_score='27').save()
    Game(game_id='154',	week='11',	day='Sunday',	date='43786',	away_team=hou,	away_spread='4.5',
         home_team=bal,	home_spread='-4.5',	over_under='50',	away_score='7',	home_score='41').save()
    Game(game_id='155',	week='11',	day='Sunday',	date='43786',	away_team=jax,	away_spread='2.5',
         home_team=ind,	home_spread='-2.5',	over_under='43.5',	away_score='13',	home_score='33').save()
    Game(game_id='156',	week='11',	day='Sunday',	date='43786',	away_team=no,	away_spread='-5.5',
         home_team=tb,	home_spread='5.5',	over_under='52',	away_score='34',	home_score='17').save()
    Game(game_id='157',	week='11',	day='Sunday',	date='43786',	away_team=nyj,	away_spread='1',
         home_team=was,	home_spread='-1',	over_under='37.5',	away_score='34',	home_score='17').save()
    Game(game_id='158',	week='11',	day='Sunday',	date='43786',	away_team=ari,	away_spread='11.5',
         home_team=sf,	home_spread='-11.5',	over_under='46',	away_score='26',	home_score='36').save()
    Game(game_id='159',	week='11',	day='Sunday',	date='43786',	away_team=cin,	away_spread='10',
         home_team=oak,	home_spread='-10',	over_under='48.5',	away_score='10',	home_score='17').save()
    Game(game_id='160',	week='11',	day='Sunday',	date='43786',	away_team=ne,	away_spread='-3.5',
         home_team=phi,	home_spread='3.5',	over_under='45.5',	away_score='17',	home_score='10').save()
    Game(game_id='161',	week='11',	day='Sunday',	date='43786',	away_team=chi,	away_spread='7.5',
         home_team=lar,	home_spread='-7.5',	over_under='41',	away_score='7',	home_score='17').save()
    Game(game_id='162',	week='11',	day='Monday',	date='43787',	away_team=kc,	away_spread='-4.5',
         home_team=lac,	home_spread='4.5',	over_under='53',	away_score='24',	home_score='17').save()
    Game(game_id='163',	week='12',	day='Thursday',	date='43790',	away_team=ind,	away_spread='3.5',
         home_team=hou,	home_spread='-3.5',	over_under='46.5',	away_score='17',	home_score='20').save()
    Game(game_id='164',	week='12',	day='Sunday',	date='43793',	away_team=car,	away_spread='8.5',
         home_team=no,	home_spread='-8.5',	over_under='48',	away_score='31',	home_score='34').save()
    Game(game_id='165',	week='12',	day='Sunday',	date='43793',	away_team=den,	away_spread='5',
         home_team=buf,	home_spread='-5',	over_under='36.5',	away_score='3',	home_score='20').save()
    Game(game_id='166',	week='12',	day='Sunday',	date='43793',	away_team=det,	away_spread='-2.5',
         home_team=was,	home_spread='2.5',	over_under='41.5',	away_score='16',	home_score='19').save()
    Game(game_id='167',	week='12',	day='Sunday',	date='43793',	away_team=mia,	away_spread='11',
         home_team=cle,	home_spread='-11',	over_under='44.5',	away_score='24',	home_score='41').save()
    Game(game_id='168',	week='12',	day='Sunday',	date='43793',	away_team=nyg,	away_spread='6',
         home_team=chi,	home_spread='-6',	over_under='40.5',	away_score='14',	home_score='19').save()
    Game(game_id='169',	week='12',	day='Sunday',	date='43793',	away_team=oak,	away_spread='-3.5',
         home_team=nyj,	home_spread='3.5',	over_under='47',	away_score='3',	home_score='34').save()
    Game(game_id='170',	week='12',	day='Sunday',	date='43793',	away_team=pit,	away_spread='-6',
         home_team=cin,	home_spread='6',	over_under='39.5',	away_score='16',	home_score='10').save()
    Game(game_id='171',	week='12',	day='Sunday',	date='43793',	away_team=tb,	away_spread='4.5',
         home_team=atl,	home_spread='-4.5',	over_under='54',	away_score='35',	home_score='22').save()
    Game(game_id='172',	week='12',	day='Sunday',	date='43793',	away_team=jax,	away_spread='3',
         home_team=ten,	home_spread='-3',	over_under='41.5',	away_score='20',	home_score='42').save()
    Game(game_id='173',	week='12',	day='Sunday',	date='43793',	away_team=dal,	away_spread='6.5',
         home_team=ne,	home_spread='-6.5',	over_under='46',	away_score='9',	home_score='13').save()
    Game(game_id='174',	week='12',	day='Sunday',	date='43793',	away_team=gb,	away_spread='3',
         home_team=sf,	home_spread='-3',	over_under='45.5',	away_score='8',	home_score='37').save()
    Game(game_id='175',	week='12',	day='Sunday',	date='43793',	away_team=sea,	away_spread='3',
         home_team=phi,	home_spread='-3',	over_under='49',	away_score='17',	home_score='9').save()
    Game(game_id='176',	week='12',	day='Monday',	date='43794',	away_team=bal,	away_spread='3',
         home_team=lar,	home_spread='-3',	over_under='46.5',	away_score='45',	home_score='6').save()
    Game(game_id='177',	week='13',	day='Thursday',	date='43797',	away_team=chi,	away_spread='-1.5',
         home_team=det,	home_spread='1.5',	over_under='38.5',	away_score='24',	home_score='20').save()
    Game(game_id='178',	week='13',	day='Thursday',	date='43797',	away_team=buf,	away_spread='7.5',
         home_team=dal,	home_spread='-7.5',	over_under='44.5',	away_score='26',	home_score='15').save()
    Game(game_id='179',	week='13',	day='Thursday',	date='43797',	away_team=no,	away_spread='-6.5',
         home_team=atl,	home_spread='6.5',	over_under='50',	away_score='26',	home_score='18').save()
    Game(game_id='180',	week='13',	day='Sunday',	date='43800',	away_team=gb,	away_spread='-6',
         home_team=nyg,	home_spread='6',	over_under='46',	away_score='31',	home_score='13').save()
    Game(game_id='181',	week='13',	day='Sunday',	date='43800',	away_team=nyj,	away_spread='-3.5',
         home_team=cin,	home_spread='3.5',	over_under='39.5',	away_score='6',	home_score='22').save()
    Game(game_id='182',	week='13',	day='Sunday',	date='43800',	away_team=oak,	away_spread='10',
         home_team=kc,	home_spread='-10',	over_under='54.5',	away_score='9',	home_score='40').save()
    Game(game_id='183',	week='13',	day='Sunday',	date='43800',	away_team=phi,	away_spread='-7.5',
         home_team=mia,	home_spread='7.5',	over_under='46',	away_score='31',	home_score='37').save()
    Game(game_id='184',	week='13',	day='Sunday',	date='43800',	away_team=sf,	away_spread='5.5',
         home_team=bal,	home_spread='-5.5',	over_under='46',	away_score='17',	home_score='20').save()
    Game(game_id='185',	week='13',	day='Sunday',	date='43800',	away_team=tb,	away_spread='1',
         home_team=jax,	home_spread='-1',	over_under='49',	away_score='28',	home_score='11').save()
    Game(game_id='186',	week='13',	day='Sunday',	date='43800',	away_team=ten,	away_spread='3',
         home_team=ind,	home_spread='-3',	over_under='43',	away_score='31',	home_score='17').save()
    Game(game_id='187',	week='13',	day='Sunday',	date='43800',	away_team=was,	away_spread='10',
         home_team=car,	home_spread='-10',	over_under='40.5',	away_score='29',	home_score='21').save()
    Game(game_id='188',	week='13',	day='Sunday',	date='43800',	away_team=lar,	away_spread='-3',
         home_team=ari,	home_spread='3',	over_under='46',	away_score='34',	home_score='7').save()
    Game(game_id='189',	week='13',	day='Sunday',	date='43800',	away_team=cle,	away_spread='-1',
         home_team=pit,	home_spread='1',	over_under='40',	away_score='13',	home_score='20').save()
    Game(game_id='190',	week='13',	day='Sunday',	date='43800',	away_team=lac,	away_spread='0',
         home_team=den,	home_spread='0',	over_under='38.5',	away_score='20',	home_score='23').save()
    Game(game_id='191',	week='13',	day='Sunday',	date='43800',	away_team=ne,	away_spread='-3.5',
         home_team=hou,	home_spread='3.5',	over_under='45',	away_score='22',	home_score='28').save()
    Game(game_id='192',	week='13',	day='Monday',	date='43801',	away_team=minn,	away_spread='3',
         home_team=sea,	home_spread='-3',	over_under='48.5',	away_score='30',	home_score='34').save()
    Game(game_id='193',	week='14',	day='Thursday',	date='43804',	away_team=dal,	away_spread='-2.5',
         home_team=chi,	home_spread='2.5',	over_under='43.5',	away_score='24',	home_score='31').save()
    Game(game_id='194',	week='14',	day='Sunday',	date='43807',	away_team=bal,	away_spread='-5.5',
         home_team=buf,	home_spread='5.5',	over_under='43',	away_score='24',	home_score='17').save()
    Game(game_id='195',	week='14',	day='Sunday',	date='43807',	away_team=car,	away_spread='2',
         home_team=atl,	home_spread='-2',	over_under='48',	away_score='20',	home_score='40').save()
    Game(game_id='196',	week='14',	day='Sunday',	date='43807',	away_team=cin,	away_spread='8',
         home_team=cle,	home_spread='-8',	over_under='42.5',	away_score='19',	home_score='27').save()
    Game(game_id='197',	week='14',	day='Sunday',	date='43807',	away_team=den,	away_spread='9.5',
         home_team=hou,	home_spread='-9.5',	over_under='41.5',	away_score='38',	home_score='24').save()
    Game(game_id='198',	week='14',	day='Sunday',	date='43807',	away_team=det,	away_spread='13',
         home_team=minn,	home_spread='-13',	over_under='43.5',	away_score='7',	home_score='20').save()
    Game(game_id='199',	week='14',	day='Sunday',	date='43807',	away_team=ind,	away_spread='3.5',
         home_team=tb,	home_spread='-3.5',	over_under='49.5',	away_score='35',	home_score='38').save()
    Game(game_id='200',	week='14',	day='Sunday',	date='43807',	away_team=mia,	away_spread='5.5',
         home_team=nyj,	home_spread='-5.5',	over_under='43.5',	away_score='21',	home_score='22').save()
    Game(game_id='201',	week='14',	day='Sunday',	date='43807',	away_team=sf,	away_spread='3.5',
         home_team=no,	home_spread='-3.5',	over_under='45.5',	away_score='48',	home_score='46').save()
    Game(game_id='202',	week='14',	day='Sunday',	date='43807',	away_team=was,	away_spread='14',
         home_team=gb,	home_spread='-14',	over_under='42.5',	away_score='15',	home_score='20').save()
    Game(game_id='203',	week='14',	day='Sunday',	date='43807',	away_team=lac,	away_spread='-3',
         home_team=jax,	home_spread='3',	over_under='43',	away_score='45',	home_score='10').save()
    Game(game_id='204',	week='14',	day='Sunday',	date='43807',	away_team=kc,	away_spread='3',
         home_team=ne,	home_spread='-3',	over_under='49.5',	away_score='23',	home_score='16').save()
    Game(game_id='205',	week='14',	day='Sunday',	date='43807',	away_team=pit,	away_spread='-2.5',
         home_team=ari,	home_spread='2.5',	over_under='43.5',	away_score='23',	home_score='17').save()
    Game(game_id='206',	week='14',	day='Sunday',	date='43807',	away_team=ten,	away_spread='-2.5',
         home_team=oak,	home_spread='2.5',	over_under='46.5',	away_score='42',	home_score='21').save()
    Game(game_id='207',	week='14',	day='Sunday',	date='43807',	away_team=sea,	away_spread='-2.5',
         home_team=lar,	home_spread='2.5',	over_under='46.5',	away_score='12',	home_score='28').save()
    Game(game_id='208',	week='14',	day='Monday',	date='43808',	away_team=nyg,	away_spread='8.5',
         home_team=phi,	home_spread='-8.5',	over_under='47',	away_score='17',	home_score='23').save()
    Game(game_id='209',	week='15',	day='Thursday',	date='43811',	away_team=nyj,	away_spread='15',
         home_team=bal,	home_spread='-15',	over_under='44.5',	away_score='21',	home_score='42').save()
    Game(game_id='210',	week='15',	day='Sunday',	date='43814',	away_team=buf,	away_spread='1.5',
         home_team=pit,	home_spread='-1.5',	over_under='37',	away_score='17',	home_score='10').save()
    Game(game_id='211',	week='15',	day='Sunday',	date='43814',	away_team=chi,	away_spread='5',
         home_team=gb,	home_spread='-5',	over_under='41',	away_score='13',	home_score='21').save()
    Game(game_id='212',	week='15',	day='Sunday',	date='43814',	away_team=den,	away_spread='12',
         home_team=kc,	home_spread='-12',	over_under='47',	away_score='3',	home_score='23').save()
    Game(game_id='213',	week='15',	day='Sunday',	date='43814',	away_team=hou,	away_spread='3',
         home_team=ten,	home_spread='-3',	over_under='48.5',	away_score='24',	home_score='21').save()
    Game(game_id='214',	week='15',	day='Sunday',	date='43814',	away_team=mia,	away_spread='3.5',
         home_team=nyg,	home_spread='-3.5',	over_under='46.5',	away_score='20',	home_score='36').save()
    Game(game_id='215',	week='15',	day='Sunday',	date='43814',	away_team=ne,	away_spread='-8.5',
         home_team=cin,	home_spread='8.5',	over_under='40.5',	away_score='34',	home_score='13').save()
    Game(game_id='216',	week='15',	day='Sunday',	date='43814',	away_team=phi,	away_spread='-4.5',
         home_team=was,	home_spread='4.5',	over_under='40',	away_score='37',	home_score='27').save()
    Game(game_id='217',	week='15',	day='Sunday',	date='43814',	away_team=sea,	away_spread='-6',
         home_team=car,	home_spread='6',	over_under='48.5',	away_score='30',	home_score='24').save()
    Game(game_id='218',	week='15',	day='Sunday',	date='43814',	away_team=tb,	away_spread='-3',
         home_team=det,	home_spread='3',	over_under='46.5',	away_score='38',	home_score='17').save()
    Game(game_id='219',	week='15',	day='Sunday',	date='43814',	away_team=cle,	away_spread='-2',
         home_team=ari,	home_spread='2',	over_under='46.5',	away_score='24',	home_score='38').save()
    Game(game_id='220',	week='15',	day='Sunday',	date='43814',	away_team=jax,	away_spread='5.5',
         home_team=oak,	home_spread='-5.5',	over_under='45.5',	away_score='20',	home_score='16').save()
    Game(game_id='221',	week='15',	day='Sunday',	date='43814',	away_team=atl,	away_spread='11',
         home_team=sf,	home_spread='-11',	over_under='46.5',	away_score='29',	home_score='22').save()
    Game(game_id='222',	week='15',	day='Sunday',	date='43814',	away_team=lar,	away_spread='3',
         home_team=dal,	home_spread='-3',	over_under='48',	away_score='21',	home_score='44').save()
    Game(game_id='223',	week='15',	day='Sunday',	date='43814',	away_team=minn,	away_spread='-2.5',
         home_team=lac,	home_spread='2.5',	over_under='45.5',	away_score='39',	home_score='10').save()
    Game(game_id='224',	week='15',	day='Monday',	date='43815',	away_team=ind,	away_spread='8',
         home_team=no,	home_spread='-8',	over_under='45.5',	away_score='7',	home_score='34').save()
    Game(game_id='225',	week='16',	day='Sunday',	date='43821',	away_team=bal,	away_spread='-9.5',
         home_team=cle,	home_spread='9.5',	over_under='49',	away_score='31',	home_score='15').save()
    Game(game_id='226',	week='16',	day='Sunday',	date='43821',	away_team=buf,	away_spread='6.5',
         home_team=ne,	home_spread='-6.5',	over_under='38.5',	away_score='17',	home_score='24').save()
    Game(game_id='227',	week='16',	day='Sunday',	date='43821',	away_team=car,	away_spread='6.5',
         home_team=ind,	home_spread='-6.5',	over_under='46',	away_score='6',	home_score='38').save()
    Game(game_id='228',	week='16',	day='Sunday',	date='43821',	away_team=cin,	away_spread='1',
         home_team=mia,	home_spread='-1',	over_under='46',	away_score='35',	home_score='38').save()
    Game(game_id='229',	week='16',	day='Sunday',	date='43821',	away_team=det,	away_spread='7',
         home_team=den,	home_spread='-7',	over_under='37.5',	away_score='17',	home_score='27').save()
    Game(game_id='230',	week='16',	day='Sunday',	date='43821',	away_team=hou,	away_spread='1.5',
         home_team=tb,	home_spread='-1.5',	over_under='53',	away_score='23',	home_score='20').save()
    Game(game_id='231',	week='16',	day='Sunday',	date='43821',	away_team=jax,	away_spread='7.5',
         home_team=atl,	home_spread='-7.5',	over_under='45.5',	away_score='12',	home_score='24').save()
    Game(game_id='232',	week='16',	day='Sunday',	date='43821',	away_team=lar,	away_spread='6',
         home_team=sf,	home_spread='-6',	over_under='46',	away_score='31',	home_score='34').save()
    Game(game_id='233',	week='16',	day='Sunday',	date='43821',	away_team=no,	away_spread='-3',
         home_team=ten,	home_spread='3',	over_under='51.5',	away_score='38',	home_score='28').save()
    Game(game_id='234',	week='16',	day='Sunday',	date='43821',	away_team=nyg,	away_spread='2.5',
         home_team=was,	home_spread='-2.5',	over_under='42',	away_score='41',	home_score='35').save()
    Game(game_id='235',	week='16',	day='Sunday',	date='43821',	away_team=oak,	away_spread='5.5',
         home_team=lac,	home_spread='-5.5',	over_under='47',	away_score='24',	home_score='17').save()
    Game(game_id='236',	week='16',	day='Sunday',	date='43821',	away_team=pit,	away_spread='-3',
         home_team=nyj,	home_spread='3',	over_under='39',	away_score='10',	home_score='16').save()
    Game(game_id='237',	week='16',	day='Sunday',	date='43821',	away_team=ari,	away_spread='10',
         home_team=sea,	home_spread='-10',	over_under='51',	away_score='27',	home_score='13').save()
    Game(game_id='238',	week='16',	day='Sunday',	date='43821',	away_team=dal,	away_spread='-2',
         home_team=phi,	home_spread='2',	over_under='47.5',	away_score='9',	home_score='17').save()
    Game(game_id='239',	week='16',	day='Sunday',	date='43821',	away_team=kc,	away_spread='5',
         home_team=chi,	home_spread='-5',	over_under='45',	away_score='26',	home_score='3').save()
    Game(game_id='240',	week='16',	day='Monday',	date='43822',	away_team=gb,	away_spread='4',
         home_team=minn,	home_spread='-4',	over_under='46.5',	away_score='23',	home_score='10').save()
    Game(game_id='241',	week='17',	day='Sunday',	date='43828',	away_team=atl,	away_spread='1',
         home_team=tb,	home_spread='-1',	over_under='49.5',	away_score='28',	home_score='22').save()
    Game(game_id='242',	week='17',	day='Sunday',	date='43828',	away_team=chi,	away_spread='1',
         home_team=minn,	home_spread='-1',	over_under='37.5',	away_score='21',	home_score='19').save()
    Game(game_id='243',	week='17',	day='Sunday',	date='43828',	away_team=cle,	away_spread='-2.5',
         home_team=cin,	home_spread='2.5',	over_under='45.5',	away_score='23',	home_score='33').save()
    Game(game_id='244',	week='17',	day='Sunday',	date='43828',	away_team=gb,	away_spread='-12.5',
         home_team=det,	home_spread='12.5',	over_under='43',	away_score='23',	home_score='20').save()
    Game(game_id='245',	week='17',	day='Sunday',	date='43828',	away_team=ind,	away_spread='-3.5',
         home_team=jax,	home_spread='3.5',	over_under='43',	away_score='20',	home_score='38').save()
    Game(game_id='246',	week='17',	day='Sunday',	date='43828',	away_team=lac,	away_spread='7.5',
         home_team=kc,	home_spread='-7.5',	over_under='46.5',	away_score='21',	home_score='31').save()
    Game(game_id='247',	week='17',	day='Sunday',	date='43828',	away_team=mia,	away_spread='15.5',
         home_team=ne,	home_spread='-15.5',	over_under='45',	away_score='27',	home_score='24').save()
    Game(game_id='248',	week='17',	day='Sunday',	date='43828',	away_team=no,	away_spread='-13',
         home_team=car,	home_spread='13',	over_under='48',	away_score='42',	home_score='10').save()
    Game(game_id='249',	week='17',	day='Sunday',	date='43828',	away_team=nyj,	away_spread='1.5',
         home_team=buf,	home_spread='-1.5',	over_under='36.5',	away_score='13',	home_score='6').save()
    Game(game_id='250',	week='17',	day='Sunday',	date='43828',	away_team=phi,	away_spread='-4.5',
         home_team=nyg,	home_spread='4.5',	over_under='45.5',	away_score='34',	home_score='17').save()
    Game(game_id='251',	week='17',	day='Sunday',	date='43828',	away_team=pit,	away_spread='-2',
         home_team=bal,	home_spread='2',	over_under='38',	away_score='10',	home_score='28').save()
    Game(game_id='252',	week='17',	day='Sunday',	date='43828',	away_team=ten,	away_spread='0',
         home_team=hou,	home_spread='0',	over_under='49',	away_score='35',	home_score='14').save()
    Game(game_id='253',	week='17',	day='Sunday',	date='43828',	away_team=was,	away_spread='10.5',
         home_team=dal,	home_spread='-10.5',	over_under='44.5',	away_score='16',	home_score='47').save()
    Game(game_id='254',	week='17',	day='Sunday',	date='43828',	away_team=ari,	away_spread='5.5',
         home_team=lar,	home_spread='-5.5',	over_under='45',	away_score='24',	home_score='31').save()
    Game(game_id='255',	week='17',	day='Sunday',	date='43828',	away_team=oak,	away_spread='3',
         home_team=den,	home_spread='-3',	over_under='41',	away_score='15',	home_score='16').save()
    Game(game_id='256',	week='17',	day='Sunday',	date='43828',	away_team=sf,	away_spread='-1',
         home_team=sea,	home_spread='1',	over_under='47',	away_score='26',	home_score='21').save()


def fallow(apps, schema_editor):
    Team = apps.get_model('nflanalysis', 'Team')
    Game = apps.get_model('nflanalysis', 'Game')
    Game.objects.all().delete()
    Team.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nflanalysis', '0002_remove_team_int_against'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
