# Generated by Django 3.0.7 on 2020-06-13 03:39

from django.db import migrations

# TEAM MODEL

# team_name='',
# conference='',
# division='',
# wins='',
# losses='',
# ties='',
# points_for='',
# points_against='',
# rush_td='',
# pass_td='',
# total_td='',
# pass_yards='',
# rush_yards='',
# int_for='',
# forced_fumbles='',
# fumbles_recovered='',
# sacks='',
# fumble_td='',
# int_td='',
# safeties=''

# variable = Team(team_name='', conference='', division='', wins='', losses='', ties='0', points_for='', points_against='', rush_td='', pass_td='', total_td='', pass_yards='', rush_yards='', int_for='', forced_fumbles='', fumbles_recovered='', sacks='', fumble_td='', int_td='', safeties='')

# GAME MODEL

# game_id='',
# week='',
# day='',
# date='',
# away_team = ,
# away_spread='',
# home_team = ,
# home_spread='',
# over_under='',
# away_score='',
# home_score=''


def seed(apps, schema_editor):
    Team = apps.get_model('nflanalysis', 'Team')
    Game = apps.get_model('nflanalysis', 'Game')

    sf = Team(team_name='San Francisco 49ers', conference='NFC', division='West', wins='13', losses='3', ties='0', points_for='479', points_against='310', rush_td='23', pass_td='28',
              total_td='56', pass_yards='4029', rush_yards='2305', int_for='12', forced_fumbles='23', fumbles_recovered='15', sacks='36', fumble_td='2', int_td='3', safeties='0')
    chi = Team(team_name='Chicago Bears', conference='NFC', division='North', wins='8', losses='8', ties='0', points_for='280', points_against='298', rush_td='8', pass_td='20',
               total_td='30', pass_yards='3573', rush_yards='1458', int_for='10', forced_fumbles='12', fumbles_recovered='9', sacks='45', fumble_td='0', int_td='1', safeties='1')
    cin = Team(team_name='Cincinnati Bengals', conference='AFC', division='North', wins='2', losses='14', ties='0', points_for='279', points_against='420', rush_td='9', pass_td='18',
               total_td='28', pass_yards='3994', rush_yards='1517', int_for='11', forced_fumbles='9', fumbles_recovered='5', sacks='48', fumble_td='0', int_td='0', safeties='1')
    buf = Team(team_name='Buffalo Bills', conference='AFC', division='East', wins='10', losses='6', ties='0', points_for='314', points_against='259', rush_td='13', pass_td='21',
               total_td='35', pass_yards='3476', rush_yards='2054', int_for='14', forced_fumbles='16', fumbles_recovered='9', sacks='40', fumble_td='0', int_td='0', safeties='1')
    den = Team(team_name='Denver Broncos', conference='AFC', division='West', wins='7', losses='9', ties='0', points_for='282', points_against='316', rush_td='11', pass_td='16',
               total_td='28', pass_yards='3401', rush_yards='1662', int_for='10', forced_fumbles='9', fumbles_recovered='6', sacks='41', fumble_td='1', int_td='0', safeties='0')
    cle = Team(team_name='Cleveland Browns', conference='AFC', division='North', wins='6', losses='10', ties='0', points_for='335', points_against='393', rush_td='15', pass_td='22',
               total_td='38',	pass_yards='3847', rush_yards='1901', int_for='14', forced_fumbles='12', fumbles_recovered='6', sacks='41', fumble_td='0', int_td='1', safeties='0')
    tb = Team(team_name='Tampa Bay Buccaneers', conference='NFC', division='South', wins='7', losses='9', ties='0', points_for='458', points_against='449', rush_td='15', pass_td='33',
              total_td='54', pass_yards='5127', rush_yards='1521', int_for='12', forced_fumbles='21', fumbles_recovered='16', sacks='47', fumble_td='4', int_td='2', safeties='0')
    ari = Team(team_name='Arizona Cardinals', conference='NFC', division='West', wins='5', losses='10', ties='1', points_for='361', points_against='442', rush_td='18', pass_td='20',
               total_td='38', pass_yards='3797', rush_yards='1990', int_for='7', forced_fumbles='19', fumbles_recovered='10', sacks='50', fumble_td='0', int_td='0', safeties='0')
    lac = Team(team_name='Los Angeles Chargers', conference='AFC', division='West', wins='5', losses='11', ties='0', points_for='337', points_against='345', rush_td='12',
               pass_td='24', total_td='37',	pass_yards='4648',	rush_yards='1453', int_for='11', forced_fumbles='6', fumbles_recovered='3', sacks='34', fumble_td='0', int_td='0', safeties='0')
    kc = Team(team_name='Kansas City Chiefs', conference='AFC', division='West', wins='12', losses='4', ties='0', points_for='451',	points_against='308', rush_td='16', pass_td='30',
              total_td='50', pass_yards='4690', rush_yards='1569', int_for='16', forced_fumbles='13', fumbles_recovered='7', sacks='25', fumble_td='2', int_td='1', safeties='0')
    ind = Team(team_name='Indianapolis Colts',	conference='AFC',	division='South',	wins='7',	losses='9',	ties='0',	points_for='361',	points_against='373',	rush_td='17',	pass_td='22',
               total_td='42',	pass_yards='3314',	rush_yards='2130',	int_for='15',	forced_fumbles='14',	fumbles_recovered='8',	sacks='32',	fumble_td='0',	int_td='1',	safeties='2')
    dal = Team(team_name='Dallas Cowboys',	conference='NFC',	division='East',	wins='8',	losses='8',	ties='0',	points_for='434',	points_against='321',	rush_td='18',	pass_td='30',
               total_td='49',	pass_yards='4902',	rush_yards='2153',	int_for='7',	forced_fumbles='14',	fumbles_recovered='10',	sacks='23',	fumble_td='1',	int_td='0',	safeties='0')
    mia = Team(team_name='Miami Dolphins',	conference='AFC',	division='East',	wins='5',	losses='11',	ties='0',	points_for='306',	points_against='494',	rush_td='10',	pass_td='22',
               total_td='34',	pass_yards='4117',	rush_yards='1156',	int_for='13',	forced_fumbles='9',	fumbles_recovered='3',	sacks='58',	fumble_td='0',	int_td='1',	safeties='1')
    phi = Team(team_name='Philadelphia Eagles',	conference='NFC',	division='East',	wins='9',	losses='7',	ties='0',	points_for='385',	points_against='354',	rush_td='16',	pass_td='27',
               total_td='46',	pass_yards='4063',	rush_yards='1939',	int_for='11',	forced_fumbles='15',	fumbles_recovered='9',	sacks='37',	fumble_td='2',	int_td='1',	safeties='0')
    atl = Team(team_name='Atlanta Falcons',	conference='NFC',	division='South',	wins='7',	losses='9',	ties='0',	points_for='381',	points_against='399',	rush_td='10',	pass_td='29',
               total_td='42',	pass_yards='5049',	rush_yards='1361',	int_for='12',	forced_fumbles='17',	fumbles_recovered='8',	sacks='50',	fumble_td='1',	int_td='1',	safeties='0')
    nyg = Team(team_name='New York Giants',	conference='NFC',	division='East',	wins='4',	losses='12',	ties='0',	points_for='341',	points_against='451',	rush_td='11',	pass_td='30',
               total_td='44',	pass_yards='4070',	rush_yards='1685',	int_for='10',	forced_fumbles='9',	fumbles_recovered='6',	sacks='43',	fumble_td='1',	int_td='1',	safeties='1')
    jax = Team(team_name='Jacksonville Jaguars',	conference='AFC',	division='South',	wins='6',	losses='10',	ties='0',	points_for='300',	points_against='397',	rush_td='3',	pass_td='24',
               total_td='29',	pass_yards='4023',	rush_yards='1708',	int_for='10',	forced_fumbles='13',	fumbles_recovered='9',	sacks='42',	fumble_td='1',	int_td='1',	safeties='0')
    nyj = Team(team_name='New York Jets',	conference='AFC',	division='East',	wins='7',	losses='9',	ties='0',	points_for='276',	points_against='359',	rush_td='6',	pass_td='19',
               total_td='31',	pass_yards='3443',	rush_yards='1257',	int_for='12',	forced_fumbles='10',	fumbles_recovered='9',	sacks='52',	fumble_td='2',	int_td='3',	safeties='2')
    det = Team(team_name='Detroit Lions',	conference='NFC',	division='North',	wins='3',	losses='12',	ties='1',	points_for='341',	points_against='423',	rush_td='7',	pass_td='28',
               total_td='38',	pass_yards='4187',	rush_yards='1649',	int_for='7',	forced_fumbles='16',	fumbles_recovered='11',	sacks='43',	fumble_td='1',	int_td='0',	safeties='0')
    gb = Team(team_name='Green Bay Packers',	conference='NFC',	division='North',	wins='13',	losses='3',	ties='0',	points_for='376',	points_against='313',	rush_td='18',	pass_td='26',
              total_td='44',	pass_yards='4017',	rush_yards='1795',	int_for='17',	forced_fumbles='12',	fumbles_recovered='7',	sacks='36',	fumble_td='0',	int_td='0',	safeties='0')
    car = Team(team_name='Carolina Panthers',	conference='NFC',	division='South',	wins='5',	losses='11',	ties='0',	points_for='340',	points_against='470',	rush_td='20',	pass_td='17',
               total_td='38',	pass_yards='4134',	rush_yards='1819',	int_for='14',	forced_fumbles='8',	fumbles_recovered='7',	sacks='58',	fumble_td='1',	int_td='0',	safeties='2')
    ne = Team(team_name='New England Patriots',	conference='AFC',	division='East',	wins='12',	losses='4',	ties='0',	points_for='420',	points_against='225',	rush_td='17',	pass_td='25',
              total_td='49',	pass_yards='4153',	rush_yards='1703',	int_for='25',	forced_fumbles='15',	fumbles_recovered='11',	sacks='28',	fumble_td='2',	int_td='3',	safeties='1')
    oak = Team(team_name='Oakland Raiders',	conference='AFC',	division='West',	wins='7',	losses='9',	ties='0',	points_for='313',	points_against='419',	rush_td='13',	pass_td='22',
               total_td='37',	pass_yards='4110',	rush_yards='1893',	int_for='9',	forced_fumbles='9',	fumbles_recovered='6',	sacks='29',	fumble_td='0',	int_td='2',	safeties='0')
    lar = Team(team_name='Los Angeles Rams',	conference='NFC',	division='West',	wins='9',	losses='7',	ties='0',	points_for='394',	points_against='364',	rush_td='20',	pass_td='22',
               total_td='46',	pass_yards='4669',	rush_yards='1499',	int_for='13',	forced_fumbles='15',	fumbles_recovered='11',	sacks='22',	fumble_td='2',	int_td='2',	safeties='1')
    bal = Team(team_name='Baltimore Ravens',	conference='AFC',	division='North',	wins='14',	losses='2',	ties='0',	points_for='531',	points_against='282',	rush_td='21',	pass_td='37',
               total_td='64',	pass_yards='3350',	rush_yards='3296',	int_for='13',	forced_fumbles='15',	fumbles_recovered='12',	sacks='28',	fumble_td='4',	int_td='2',	safeties='1')
    was = Team(team_name='Washington Redskins',	conference='NFC',	division='East',	wins='3',	losses='13',	ties='0',	points_for='266',	points_against='435',	rush_td='9',	pass_td='18',
               total_td='28',	pass_yards='3205',	rush_yards='1583',	int_for='13',	forced_fumbles='16',	fumbles_recovered='9',	sacks='50',	fumble_td='0',	int_td='0',	safeties='0')
    no = Team(team_name='New Orleans Saints',	conference='NFC',	division='South',	wins='13',	losses='3',	ties='0',	points_for='458',	points_against='341',	rush_td='12',	pass_td='36',
              total_td='52',	pass_yards='4431',	rush_yards='1738',	int_for='13',	forced_fumbles='11',	fumbles_recovered='10',	sacks='25',	fumble_td='1',	int_td='2',	safeties='1')
    sea = Team(team_name='Seattle Seahawks',	conference='NFC',	division='West',	wins='11',	losses='5',	ties='0',	points_for='405',	points_against='398',	rush_td='15',	pass_td='31',
               total_td='49',	pass_yards='4110',	rush_yards='2200',	int_for='16',	forced_fumbles='19',	fumbles_recovered='16',	sacks='48',	fumble_td='1',	int_td='2',	safeties='0')
    pit = Team(team_name='Pittsburgh Steelers',	conference='AFC',	division='North',	wins='8',	losses='8',	ties='0',	points_for='289',	points_against='303',	rush_td='7',	pass_td='18',
               total_td='29',	pass_yards='3214',	rush_yards='1447',	int_for='20',	forced_fumbles='22',	fumbles_recovered='18',	sacks='32',	fumble_td='2',	int_td='1',	safeties='0')
    hou = Team(team_name='Houston Texans',	conference='AFC',	division='South',	wins='10',	losses='6',	ties='0',	points_for='378',	points_against='385',	rush_td='17',	pass_td='27',
               total_td='46',	pass_yards='4083',	rush_yards='2009',	int_for='12',	forced_fumbles='14',	fumbles_recovered='10',	sacks='49',	fumble_td='0',	int_td='2',	safeties='0')
    ten = Team(team_name='Tennessee Titans',	conference='AFC',	division='South',	wins='9',	losses='7',	ties='0',	points_for='402',	points_against='331',	rush_td='21',	pass_td='29',
               total_td='54',	pass_yards='3956',	rush_yards='2223',	int_for='14',	forced_fumbles='11',	fumbles_recovered='9',	sacks='56',	fumble_td='2',	int_td='1',	safeties='1')
    minn = Team(team_name='Minnesota Vikings',	conference='NFC',	division='North',	wins='10',	losses='6',	ties='0',	points_for='407',	points_against='303',	rush_td='19',	pass_td='26',
                total_td='47',	pass_yards='3729',	rush_yards='2133',	int_for='17',	forced_fumbles='19',	fumbles_recovered='14',	sacks='28',	fumble_td='1',	int_td='1',	safeties='1')
    sf.save()
    chi.save()
    cin.save()
    buf.save()
    den.save()
    cle.save()
    tb.save()
    ari.save()
    lac.save()
    kc.save()
    ind.save()
    dal.save()
    mia.save()
    phi.save()
    atl.save()
    nyg.save()
    jax.save()
    nyj.save()
    det.save()
    gb.save()
    car.save()
    ne.save()
    oak.save()
    lar.save()
    bal.save()
    was.save()
    no.save()
    sea.save()
    pit.save()
    hou.save()
    ten.save()
    minn.save()


def fallow(apps, schema_editor):
    Team = apps.get_model('nflanalysis', 'Team')
    Game = apps.get_model('nflanalysis', 'Game')
    Game.objects.all().delete()
    Team.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nflanalysis', '0002_remove_team_int_against'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
